### ISSUE TITLE
Implementation data parser for google fit

### ISSUE THREAD

**Issue by Thanni123** [christianreiser/InsightMe#12]
Auslesen und Konvertierung von Google Fit Daten in JSON-Format bzw. CSV-Format. 
-> lokal auf dem Gerät abspeichern für die spätere Berechnungen

**Comment by christianreiser** [comment]
let's to csv in the following format

date                            | heartrate | stepcount | sleepduration
--------------------------------------------------------------------------------
2021-12-31 23:59:59 | 55            | 10000       | 1235774
2021-12-31 23:59      | 55            | 10000       | 1235774
2021-12-31                | 55            | 10000       | 1235774

**Comment by christianreiser** [comment]
aggregate data to one row for each day (mean, sum, min, max)
